login: &login
  adapter: postgresql
  host: localhost
  port: 5432
  encoding: utf8
  pool: 5
  timeout: 5000
  database: nc_development
  username: unit
  password: unit237942

development:
  <<: *login
