# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05a50e0c3ae514d1e3118cd0bbde70953500dc5e2c73b7dcf9bfbe1e87d32bf9ef4ce4c4ec408a6474b50f52047b9ee942e5fbbd42b9cf3f49e806b5581f0a71

test:
  secret_key_base: 756ecd3281a4cf17a8d9d115d40fe9d6e804b7c079d75a066dc9bd4d06a979514cd2399453771315fd266969900876541ea530b06b12ce29af17e0162fdcbb64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
